// Abre PostgreSQL y crea las tres tablas si todavía no existen.
// users guarda la cuenta. login_codes guarda un solo código. sessions guarda el token vigente.
package database

import (
	"database/sql"
	"fmt"

	_ "github.com/jackc/pgx/v5/stdlib"
)

// Open conecta con DATABASE_URL y comprueba que Postgres responda.
func Open(dsn string) (*sql.DB, error) {
	conn, err := sql.Open("pgx", dsn)
	if err != nil {
		return nil, err
	}
	if err = conn.Ping(); err != nil {
		return nil, fmt.Errorf("conectar postgres: %w", err)
	}
	return conn, nil
}

// Migrate crea las tablas.
// El id de users es un entero que Postgres incrementa solo.
func Migrate(conn *sql.DB) error {
	_, err := conn.Exec(`
		CREATE TABLE IF NOT EXISTS users (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			first_name TEXT NOT NULL, last_name TEXT NOT NULL,
			identification TEXT NOT NULL UNIQUE, phone TEXT NOT NULL DEFAULT '',
			correo TEXT NOT NULL DEFAULT '', password_hash TEXT NOT NULL
		);
		ALTER TABLE users DROP COLUMN IF EXISTS created_at;
		DO $$
		BEGIN
			IF EXISTS (
				SELECT 1 FROM information_schema.columns
				WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'gmail'
			) THEN
				ALTER TABLE users RENAME COLUMN gmail TO correo;
			END IF;
		END $$;
		DROP INDEX IF EXISTS users_gmail_unique;
		CREATE TABLE IF NOT EXISTS login_codes (
			user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
			code_hash TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL,
			attempts INT NOT NULL DEFAULT 0, channel TEXT NOT NULL DEFAULT 'correo',
			sent_at TIMESTAMPTZ NOT NULL DEFAULT now()
		);
		ALTER TABLE login_codes ADD COLUMN IF NOT EXISTS channel TEXT NOT NULL DEFAULT 'correo';
		ALTER TABLE login_codes ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ NOT NULL DEFAULT now();
		CREATE TABLE IF NOT EXISTS sessions (
			user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
			last_seen TIMESTAMPTZ NOT NULL,
			token TEXT NOT NULL DEFAULT ''
		);
		ALTER TABLE sessions ADD COLUMN IF NOT EXISTS token TEXT NOT NULL DEFAULT '';
	`)
	return err
}
